merchant1 = Merchant.create!(name: 'Cat Stuff')
discount1 = Discount.create!(percentage_discount: 20, quantity_threshold: 10, merchant_id: merchant1.id)
discount2 = Discount.create!(percentage_discount: 25, quantity_threshold: 15, merchant_id: merchant1.id)
discount3 = Discount.create!(percentage_discount: 30, quantity_threshold: 20, merchant_id: merchant1.id)
item1 = Item.create!(name: "Whisker Lickers", description: "Cat Treats", unit_price: 7, status: 1, merchant_id: merchant1.id)
item2 = Item.create!(name: "Glitter Ball", description: "Cat Toy", unit_price: 2, status: 1, merchant_id: merchant1.id)
item3 = Item.create!(name: "Tidy Cat Litter", description: "Cat Litter", unit_price: 10, status: 1, merchant_id: merchant1.id)

merchant2 = Merchant.create!(name: 'Dog Stuff')
discount4 = Discount.create!(percentage_discount: 10, quantity_threshold: 5, merchant_id: merchant2.id)
discount5 = Discount.create!(percentage_discount: 20, quantity_threshold: 10, merchant_id: merchant2.id)
discount6 = Discount.create!(percentage_discount: 25, quantity_threshold: 15, merchant_id: merchant2.id)
item4 = Item.create!(name: "Beggin Strips", description: "Dog Treats", unit_price: 6, status: 1, merchant_id: merchant2.id)
item5 = Item.create!(name: "Rope Pull", description: "Dog Toy", unit_price: 9, status: 1, merchant_id: merchant2.id)
item6 = Item.create!(name: "Plaid leash", description: "Leash", unit_price: 12, status: 1, merchant_id: merchant2.id)

merchant3 = Merchant.create!(name: 'Bird Stuff')
discount7 = Discount.create!(percentage_discount: 30, quantity_threshold: 7, merchant_id: merchant3.id)
discount8 = Discount.create!(percentage_discount: 40, quantity_threshold: 17, merchant_id: merchant3.id)
discount9 = Discount.create!(percentage_discount: 50, quantity_threshold: 27, merchant_id: merchant3.id)
item7 = Item.create!(name: "Birdie Chow", description: "Bird Seed", unit_price: 11, status: 1, merchant_id: merchant3.id)
item8 = Item.create!(name: "Rollie Penguin", description: "Bird Toy", unit_price: 8, status: 1, merchant_id: merchant3.id)
item9 = Item.create!(name: "Cuddle Bone", description: "Bird Treat", unit_price: 4, status: 1, merchant_id: merchant3.id)
